import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS, SIZES} from '../../constants';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },

  search: {
    height: height * 0.026,
    width: width * 0.06,
    marginHorizontal: width * 0.03,
    resizeMode: 'contain',
    tintColor: COLORS.gray30,
  },
  name: {
    height: height * 0.065,
    width: width * 0.92,
    marginTop: height * 0.01,
    marginBottom: height * 0.015,
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
  },
  placeholder: {
    width: width * 0.75,
    fontFamily: FONTS.regular,
    color: COLORS.gray40,
    fontSize: 14,
    marginBottom: -3,
  },
  switchrow: {
    width: width * 0.92,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    // borderWidth: 1,
    justifyContent: 'space-between',
  },
  service_row: {
    width: width * 0.92,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    alignSelf: 'center',
    columnGap: SIZES.width * .038,
    // borderWidth: 1,
    // borderColor: COLORS.black
  }, 
  switchbox: {
    width: width * 0.45,
    justifyContent: 'center',
    alignItems: 'center',
    height: height * 0.056,
    borderWidth: 1,
    borderColor: COLORS.gray40,
    // backgroundColor: COLORS.gray20,
    borderRadius: 10,
    marginVertical: 1,
  },
  switchtext: {
    fontSize: 14,
    ...FONTS.sixHundred,
    color: COLORS.gray40,
    marginBottom: -4,
  },
  text5: {
    margin: width * 0.03,
    fontFamily: FONTS.medium,
    fontSize: 15,
    marginLeft: width * 0.04,
    color: COLORS.black,
    marginBottom: -1,
  },
  img3: {
    height: height * 0.24,
    width: width * 0.92,
    borderRadius: 10,
    resizeMode: 'stretch',
    marginHorizontal: width * 0.04,
    marginBottom: height * 0.03,
    marginTop: height * 0.01,
  },
  serviceBox: {
    width: width * 0.4,
    marginTop: height * 0.02,
    marginBottom: height * 0.02,
    borderWidth: 1,
    borderColor: COLORS.gray20,
    paddingBottom: height * 0.01,
    borderRadius: 10,
    marginLeft: width * 0.04,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  serviceimg: {
    width: width * 0.4,
    height: width * 0.4,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    alignSelf: 'center',
  },
  servicetitle: {
    color: COLORS.black,
    fontSize: 17,
    ...FONTS.fiveHundred,
    textAlign: 'center',
    width: width * 0.92,
    marginTop: height * 0.03,
    alignSelf: 'center',
  },
  servicesubtitle: {
    color: COLORS.black,
    fontSize: 13,
    ...FONTS.fourHundred,
    textAlign: 'center',
    width: width * 0.92,
    alignSelf: 'center',
  },
  serviceboxtitle: {
    color: COLORS.black,
    fontSize: 13,
    ...FONTS.fiveHundred,
    textAlign: 'center',
    width: width * 0.38,
    marginTop: height * 0.01,
    alignSelf: 'center',
    height: height * 0.055,
  },
  serviceboxsubtitle: {
    color: COLORS.black,
    fontSize: 12,
    ...FONTS.fourHundred,
    textAlign: 'center',
    width: width * 0.38,
    alignSelf: 'center',
    height: height * 0.055,
  },
});
