import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  back_btn: {
    width: width * 0.1,
    height: width * 0.1,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: width * 0.02,
    // borderWidth: 1,
  },
  rightarrow: {
    height: width * 0.05,
    width: width * 0.05,
    // marginTop: height * 0.02,
    tintColor: COLORS.primary,
    resizeMode: 'contain',
  },
  text1: {
    margin: width * 0.025,
    marginLeft: width * 0.03,
    fontSize: 13,
    width: width * 0.8,
    fontFamily: FONTS.medium,
    color: COLORS.gray,
  },
  text2: {
    // margin: width * 0.032,
    marginRight: width * 0.03,
    fontSize: 13,
    color: '#EE2761',
    fontFamily: FONTS.medium,
  },

  t1: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: COLORS.prime,
    borderRadius: 10,
    height: height * 0.06,
    width: width * 0.4,
    marginVertical: height * 0.03,
  },
  text2: {
    fontSize: width * 0.042,
    fontFamily: FONTS.semiBold,
    color: COLORS.white,
    marginBottom: -4,
  },

  btn: {
    width: width * 0.9,
    marginVertical: height * 0.04,
    alignSelf: 'center',
    borderRadius: 15,
  },

  box2: {
    width: width * 0.92,
    borderWidth: 1,
    borderRadius: 10,
    marginVertical: width * 0.03,
    alignSelf: 'center',
    flexDirection: 'row',
    borderColor: '#EE2761',
    justifyContent: 'space-between',
  },
  view_btn: {
    // width: width * 0.92,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    marginRight: width * 0.03,
    // justifyContent: 'space-between',
  },
  // ======================

  pymtname: {
    fontSize: 16,
    color: COLORS.black,
    fontFamily: FONTS.semiBold,
    marginBottom: 2,
  },
  pymtSubtitle: {
    fontSize: 12,
    color: COLORS.gray,
    fontFamily: FONTS.medium,
  },
  pymentBox: {
    flexDirection: 'row',
    alignSelf: 'center',
    elevation: 4,
    backgroundColor: COLORS.white,
    height: height * 0.1,
    width: width * 0.92,
    alignItems: 'center',
    borderRadius: 15,
    marginVertical: height * 0.015,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  pymtIcon: {
    height: height * 0.05,
    width: width * 0.12,
    resizeMode: 'contain',
    marginHorizontal: width * 0.03,
  },
  radioBox: {
    height: width * 0.055,
    width: width * 0.055,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    height: width * 0.038,
    width: width * 0.038,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
  },
  productContainer: {
    marginVertical: height * 0.015,
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: FONTS.semiBold,
    color: COLORS.black,
    marginLeft: width * 0.04,
    marginBottom: 10,
  },
  productCard: {
    width: width * 0.35,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginRight: 12,
    elevation: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.lightGray31,
    marginBottom: 8,
  },
  productThumb: {
    width: '100%',
    height: height * 0.1,
    resizeMode: 'cover',
    backgroundColor: COLORS.lightGray3,
  },
  productInfo: {
    padding: 8,
  },
  productTitle: {
    fontSize: 12,
    fontFamily: FONTS.medium,
    color: COLORS.black,
  },
  productPrice: {
    fontSize: 11,
    fontFamily: FONTS.bold,
    color: COLORS.primary,
    marginTop: 2,
  },
  totalSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: width * 0.04,
    marginTop: 10,
    backgroundColor: '#fff5f7',
    paddingVertical: 12,
    marginHorizontal: width * 0.04,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EE276133',
  },
  totalText: {
    fontSize: 13,
    fontFamily: FONTS.medium,
    color: COLORS.gray,
  },
  // empty state
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: width * 0.05,
    marginTop: height * 0.1,
  },
  emptyImage: {
    width: width * 0.7,
    height: height * 0.3,
    resizeMode: 'contain',
    marginBottom: height * 0.03,
  },
  emptyTitle: {
    fontSize: 22,
    fontFamily: FONTS.semiBold,
    color: COLORS.black,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 14,
    fontFamily: FONTS.regular,
    color: COLORS.gray,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: height * 0.05,
  },
});
